#if !defined(_ACTION_ID_H_)
#define _ACTION_ID_H_


typedef struct  
{
	short	ActionNum;
	short	Action[64];
}ACTIONGROUP;

#define ACT_UICHANGE					0x01
#define ACT_UISTACK						0x02
#define ACT_FACECHANGE					0x03
#define ACT_EXIT						-1


#define ACT_READLOGINNAME				0x11
#define ACT_READLOGINCODE				ACT_READLOGINNAME				+1


#define ACT_READREGISTERNAME			ACT_READLOGINCODE				+1
#define ACT_READREGISTERCODE			ACT_READREGISTERNAME			+1	
#define ACT_READREGISTERCODE2			ACT_READREGISTERCODE			+1	
#define ACT_READREGISTEREMAIL			ACT_READREGISTERCODE2			+1	
#define ACT_READREGISTERAGE				ACT_READREGISTEREMAIL			+1	

#define ACT_REGISTEREXIT				ACT_READREGISTERAGE				+1	

#define ACT_READPLAYERINFO				ACT_REGISTEREXIT				+1	
#define ACT_SETPLAYERINFO				ACT_READPLAYERINFO				+1	


#define ACT_SENDLOGIN					ACT_SETPLAYERINFO				+1	
#define ACT_RECEIVELOGIN				ACT_SENDLOGIN					+1	
#define ACT_SENDREGISTER				ACT_RECEIVELOGIN				+1	
#define ACT_RECEIVEREADREGISTER			ACT_SENDREGISTER				+1	
#define ACT_SENDPLAYERINFO				ACT_RECEIVEREADREGISTER			+1	
#define ACT_RECEIVEPLAYERINFO			ACT_SENDPLAYERINFO				+1	


#endif